### ISSUE TITLE
Expand Basic Usage Guide

### ISSUE THREAD

**Issue by jwritz** [calumari/fivem-vue-boilerplate#4]
Additional explanation of usage of some of the included features would be very helpful.  For example, a simple guide that shows how to use the the Nui emulate function.

**Comment by calumari** [comment]
Hey, sorry the late response. I am no longer involved in FiveM and apart from the occasional dependency bump this project is  unmaintained. 

I did make an example for my FiveM React boilerplate. The concept is fairly similar, however it uses Redux. 

Check out https://github.com/calumari/fivem-react-boilerplate/tree/master/example if you're interested.

**Comment by jwritz** [comment]
Thank you! I will look into that
